apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: express-02
  namespace: argocd
spec:
  project: default
  source:
    reporURL: https://github.com/ianPlasabas/express-02.git
    targetRevision: HEAD
    path: express-02
  destination:
    server: https://kubernetes.default.svc
    namespace: express-02
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true