apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: your_mongo_user # Replace with your desired username
  password: your_strong_password # Replace with your desired password