apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ianPlasabas/argocd-config.git
    targetRevision: HEAD
    path: proj-01-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: proj-01-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfheal: true
      prune: true
      

