apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3000
  selector:
        name: express-01-pod
        project: express-01
        environment: development
